name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Unit Tests
        run: npm test

      - name: Lint (ESLint)
        run: npx eslint .

      - name: Dependency Scan
        run: npm audit --audit-level=high

  docker-build-scan-deploy:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          COMMIT_SHA=${{ github.sha }}
          echo "Building Docker image with tag: $COMMIT_SHA"
          docker build \
            --build-arg COMMIT_SHA=$COMMIT_SHA \
            -t nisha2706/nodejs-app:$COMMIT_SHA \
            -t nisha2706/nodejs-app:latest .

      - name: Push Docker Image
        run: |
          COMMIT_SHA=${{ github.sha }}
          docker push nisha2706/nodejs-app:$COMMIT_SHA
          docker push nisha2706/nodejs-app:latest

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: nisha2706/nodejs-app:${{ github.sha }}
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          COMMIT_SHA=${{ github.sha }}

          # Update Deployment image
          kubectl set image deployment/nodejs-app \
            nodejs-app=nisha2706/nodejs-app:$COMMIT_SHA

          # Update COMMIT_SHA env in deployment
          kubectl set env deployment/nodejs-app COMMIT_SHA=$COMMIT_SHA

          # Wait for rollout
          kubectl rollout status deployment/nodejs-app

